services:
    bot:
        build: .
        volumes:
            - type: bind
              source: ./saved_media
              target: /usr/src/app/saved_media
              bind:
                  create_host_path: true
            - type: bind
              source: ./logs
              target: /usr/src/app/logs
              bind:
                  create_host_path: true
        environment:
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            PIXIV_REFRESH_TOKEN: ${PIXIV_REFRESH_TOKEN}

volumes:
    media:
    logs:
