services:
    bot:
        user: "${UID}:${GID}"
        build: .
        container_name: discord-image-downloader
        environment:
            DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
            PIXIV_REFRESH_TOKEN: ${PIXIV_REFRESH_TOKEN}
        volumes:
            - ./saved_media:/usr/src/app/saved_media
            - ./logs:/usr/src/app/logs